# Generated by Django 4.2.23 on 2025-09-29 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ', 'verbose_name_plural': 'رنگ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'تصویر گالری', 'verbose_name_plural': 'تصاویر گالری'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'سایز', 'verbose_name_plural': 'سایزها'},
        ),
        migrations.RemoveField(
            model_name='color',
            name='hex_code',
        ),
        migrations.AddField(
            model_name='color',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='کد رنگ (مثلاً #FF0000)'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نمایش در سایت'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام رنگ'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.IntegerField(default=0, help_text='عدد کمتر = نمایش زودتر', verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان تصویر (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام سایز'),
        ),
    ]
