# Generated by Django 4.2.23 on 2025-10-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان (اختیاری)')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر بنر')),
                ('link', models.URLField(blank=True, help_text='لینک به صفحه محصول یا دسته\u200cبندی', null=True, verbose_name='لینک (اختیاری)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنرهای تبلیغاتی',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اسلاید')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='home_sliders/', verbose_name='تصویر اسلاید')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک (اختیاری)')),
                ('slider_type', models.CharField(choices=[('slider1', 'اسلایدر اول'), ('slider2', 'اسلایدر دوم')], default='slider1', max_length=10, verbose_name='نوع اسلایدر')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اسلایدر صفحه اصلی',
                'verbose_name_plural': 'اسلایدرهای صفحه اصلی',
                'ordering': ['slider_type', 'order', '-created_at'],
            },
        ),
    ]
