# Generated by Django 4.2.23 on 2025-10-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_banner_homeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_in_homepage',
            field=models.CharField(choices=[('always', 'همیشه نمایش داده شود'), ('never', 'هرگز نمایش داده نشود'), ('conditional', 'فقط در صورت محصول داشتن')], default='always', max_length=15, verbose_name='نحوه نمایش در صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='category',
            name='homepage_order',
            field=models.IntegerField(default=0, help_text='عدد کمتر = نمایش زودتر', verbose_name='ترتیب نمایش در صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='دسته\u200cبندی\u200cهای ویژه در جایگاه بهتری نمایش داده می\u200cشوند', verbose_name='دسته\u200cبندی ویژه'),
        ),
    ]
