# Generated by Django 4.2.23 on 2025-10-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_category_display_in_homepage_category_homepage_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='display_in_homepage',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_homepage',
            field=models.BooleanField(default=True, help_text='اگر تیک بخورد، این دسته\u200cبندی در صفحه اصلی نمایش داده می\u200cشود', verbose_name='نمایش در صفحه اصلی'),
        ),
    ]
