# Generated by Django 4.2.23 on 2025-10-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_category_display_in_homepage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_variants',
        ),
    ]
