# Generated by Django 4.2.23 on 2025-10-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_product_has_variants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'نوع محصول', 'verbose_name_plural': 'انواع محصول'},
        ),
    ]
