# Generated by Django 4.2.23 on 2025-10-03 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0007_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ کل')),
                ('shipping_method', models.CharField(choices=[('tipax', 'تیپاکس (پس کرایه)'), ('post', 'پست پیشتاز'), ('special_post', 'پست ویژه')], default='post', max_length=20, verbose_name='روش ارسال')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه ارسال')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_authority', models.CharField(blank=True, max_length=50, verbose_name='کد مرجع پرداخت')),
                ('payment_reference', models.CharField(blank=True, max_length=50, verbose_name='شماره پیگیری')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
